[env:kitchen]
platform        = espressif32
board           = m5stickc_plus2
board_build.partitions = default.csv
framework       = arduino
upload_speed    = 1500000
monitor_speed   = 115200
lib_ldf_mode    = deep
build_flags     =
    -DARDUINO_M5StickCPlus2
    -I${PROJECT_DIR}/../shared
lib_deps        =
    m5stack/M5Unified @ ^0.2.13
